"""Scikit-learn preprocessing pipeline builders.

The preprocessor is always built from the same config-driven feature lists,
ensuring that the transformation applied during training is byte-for-byte
identical to the transformation applied during inference.

Usage pattern:
    preprocessor = build_preprocessor(
        numeric_features=config["numeric"],
        categorical_features=config["categorical"],
        binary_features=config["binary"],
        scale_numeric=config["scale"],
    )
    pipeline = Pipeline([("preprocessor", preprocessor), ("model", estimator)])
"""

from typing import List, Optional

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler


def build_numeric_transformer(scale: bool = False) -> Pipeline:
    """Numeric pipeline: median imputation, optional StandardScaler.

    Args:
        scale: Apply StandardScaler after imputation. Set True for
               distance- or gradient-sensitive models (MLPRegressor, SVR).
               Not needed for tree-based models (Random Forest, etc.).
    """
    steps: list = [("imputer", SimpleImputer(strategy="median"))]
    if scale:
        steps.append(("scaler", StandardScaler()))
    return Pipeline(steps)


def build_categorical_transformer() -> Pipeline:
    """Categorical pipeline: mode imputation + one-hot encoding.

    handle_unknown='ignore' ensures unseen categories at inference time
    are silently mapped to an all-zero vector instead of raising an error.
    """
    return Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        (
            "onehot",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False,   # return a dense array
                drop=None,             # keep full encoding (no collinearity issue with trees)
            ),
        ),
    ])


def build_binary_transformer() -> Pipeline:
    """Binary / flag-feature pipeline: fill missing values with 0.

    Binary features (0/1) generated by features.py are already scaled.
    A separate imputer step is still needed in case a flag column was
    not populated for some rows.
    """
    return Pipeline([
        ("imputer", SimpleImputer(strategy="constant", fill_value=0)),
    ])


def build_preprocessor(
    numeric_features: List[str],
    categorical_features: List[str],
    binary_features: Optional[List[str]] = None,
    scale_numeric: bool = False,
) -> ColumnTransformer:
    """Compose a ColumnTransformer for the given feature groups.

    Uses remainder='drop' so extra columns (e.g. description text,
    intermediate columns) are safely ignored and never reach the model.

    Args:
        numeric_features:     Continuous numeric columns (rooms, area, …).
        categorical_features: String / object categorical columns.
        binary_features:      Binary (0/1) flag columns; imputed but not scaled.
        scale_numeric:        Whether to StandardScale numeric columns.

    Returns:
        Configured ColumnTransformer (not yet fitted).
    """
    transformers = []

    if numeric_features:
        transformers.append((
            "num",
            build_numeric_transformer(scale=scale_numeric),
            numeric_features,
        ))

    if categorical_features:
        transformers.append((
            "cat",
            build_categorical_transformer(),
            categorical_features,
        ))

    if binary_features:
        transformers.append((
            "bin",
            build_binary_transformer(),
            binary_features,
        ))

    return ColumnTransformer(transformers=transformers, remainder="drop")
